pressure:
  mqtt_host: 127.0.0.1
  mqtt_port: 8000
  start_index : 5001
  client_count: 5000

logging:
  config: /Users/liangjiajun/Work/v-mqtt-server/v-mqtt-server-pressure/src/main/resources/config/log4j2.xml