mqtt :
  port : 1833
  ssl : false
  io_thread_count : 16
  session_thread_count: 16

  broker :
    id : 1
    ssl : false
    password_must : false
    cluster_enabled: false

logging:
  config: classpath:config/log4j2.xml