mqtt:
  id: 1
  host:
  port: 1833
  ssl: false
  ssl_password: 1017941200
  cluster_enabled: true
  is_batch_push: true
  is_batch_relay: true
  batch_relay_count: 100
  max_batch_relay_delay: 1000
  redis_key_notify: true
  password_must: false
  work_threads: 32
  push_threads: 32
  relay_push_client_threads: 32
  relay_push_server_threads: 32
  boss_io_threads: 32
  worker_io_threads: 32
  use_epoll: false
  keep_alive: 60
  so_backlog: 511
  so_keep_alive: true
  is_open_relay_server: true
  relay_host:
  relay_port: 1831
  relay_server_boss_io_threads: 1
  relay_server_worker_io_threads: 32
  relayClientWorkerGroupNThreads: 32
  relay_client_worker_io_threads : 32
  broker_id_2_url_map: "{'1':'127.0.0.1:1831','2':'127.0.0.1:1832'}"


logging:
  config: classpath:config/log4j2.xml