mqtt:
  id: 2
  host:
  port: 1834
  ssl: false
  ssl_password: 1017941200
  cluster_enabled: true
  password_must: false
  work_threads: 16
  boss_io_threads: 1
  worker_io_threads: 16
  use_epoll: false
  keep_alive: 60
  so_backlog: 511
  so_keep_alive: true

logging:
  config: classpath:config/log4j2.xml

spring:
  config:
    activate:
      on-profile:
        - dev