singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 3000
  password: null
  subscriptionsPerConnection: 50
  clientName: null
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 32
  connectionMinimumIdleSize: 24
  connectionPoolSize: 32
  database: 0
  dnsMonitoringInterval: 5000
  address: "redis://127.0.0.1:6379"

useScriptCache: true
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"
